nginx:
  build: .
  volumes:
    - ~/public_html:/usr/share/nginx/html
    - ~/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ~/config/nginx/sites:/etc/nginx/sites
  ports:
    - 8000:9000
  links:
   - hhvm
hhvm:
  image: diegomarangoni/hhvm:fastcgi
  volumes:
    - ~/config/hhvm/php.ini:/etc/hhvm/php.ini
